name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  check-version-bumped:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          cache: pip
      - run: pip install bump-my-version
      - run: git fetch origin master:refs/remotes/origin/master
      - run: curl -fsSL https://raw.githubusercontent.com/dycw/remote-scripts/refs/heads/master/scripts/check-version-bumped | sh -s

  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

  pyright:
    name: pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: latest
      - uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - run: uv sync
      - run: uv run pyright

  test-windows-and-mac:
    name: test / ${{ matrix.os }} / ${{ matrix.version }}
    env:
      CI: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: latest
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: uv sync --locked
      - run: uv run pytest --cov-report=term-missing:skip-covered -n=auto
    timeout-minutes: 60

  test-ubuntu:
    name: test / ubuntu-latest / ${{ matrix.version }}
    env:
      CI: 1
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack:latest
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: latest
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: uv sync --locked
      - run: uv run pytest --cov-report=term-missing:skip-covered -n=auto
    timeout-minutes: 60
