name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - run: ruff check --fix
      - run: ruff format

  test-windows-and-mac:
    name: test / ${{ matrix.os }} / ${{ matrix.version }}
    env:
      CI: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: uv sync
      - run: uv run pytest -n=auto src/tests/test_whenever.py src/tests/test_orjson.py src/tests/test_iterables.py
    timeout-minutes: 60

  test-ubuntu:
    name: test / ubuntu-latest / ${{ matrix.version }}
    env:
      CI: 1
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack:latest
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: uv sync
      - run: uv run pytest -n=auto src/tests/test_whenever.py src/tests/test_orjson.py src/tests/test_iterables.py
    timeout-minutes: 60
