name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test / ${{ matrix.os }} / ${{ matrix.version }}
    env:
      CI: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - run: python -m pip install uv
      - run: uv pip install --system loguru
      - run: pytest --cov-report=term-missing:skip-covered src/tests/test_loguru.py -k augment
    timeout-minutes: 60
