name: pull-request

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test / ${{ matrix.os }} / ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.version }}
      - uses: abatilo/actions-poetry@v2
      - run: poetry install
      - run: poetry run pytest
